# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 06:23
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0019_auto_20171003_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='thumbnail',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to='contents/'),
        ),
    ]
